# Generated by Django 3.2.6 on 2021-09-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='category',
        ),
    ]
